# echo 'dc-gotenberg' | md5sum | tr -cd 0-9 | grep -o '[1-79][1-79]' | head -n1
# 71
# 7100

name: dc-gotenberg

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DC_GOTENBERG_PORT:-7100}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
